RestaurantManager.WebApp/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using RestaurantManager.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace RestaurantManager.WebApp.Controllers
{
    public class RestaurantController : Controller
    {
        public IConfiguration Configuration;

        List<RestaurantVM> restaurantsList = new List<RestaurantVM>();

        public RestaurantController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        private string CN()
        {
            string cn = ControllerContext.RouteData.Values["controller"].ToString();
            return cn;
        }
        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }
        public async Task<IActionResult> Index()
        {
            string _restpath = GetHostUrl().Content + CN();

            using (var htppClient = new HttpClient())
            {
                using (var response = await htppClient.GetAsync(_restpath))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    restaurantsList = JsonConvert.DeserializeObject<List<RestaurantVM>>(apiResponse);
                }
            }
            return View(restaurantsList);
        }


        public async Task<IActionResult> Edit(int id)
        {
            string _restpath = GetHostUrl().Content + CN();

            RestaurantVM s = new RestaurantVM();
            using (var htppClient = new HttpClient())
            {
                using (var response = await htppClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    s = JsonConvert.DeserializeObject<RestaurantVM>(apiResponse);
                }
            }
            return View(s);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RestaurantVM s)
        {
            string _restpath = GetHostUrl().Content + CN();

            RestaurantVM result = new RestaurantVM();

            try
            {
                using (var htppClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(s);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");

                    using (var response = await htppClient.PutAsync($"{_restpath}/{s.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        s = JsonConvert.DeserializeObject<RestaurantVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            //string _restpath = "https://localhost:5000/SkiJumper";
            string _restpath = GetHostUrl().Content + CN();

            RestaurantVM s = new RestaurantVM();
            using (var htppClient = new HttpClient())
            {
                using (var response = await htppClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    s = JsonConvert.DeserializeObject<RestaurantVM>(apiResponse);
                }
            }
            return View(s);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(RestaurantVM s)
        {
            string _restpath = GetHostUrl().Content + CN();

            RestaurantVM result = new RestaurantVM();

            try
            {
                using (var htppClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(s);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");

                    await htppClient.DeleteAsync($"{_restpath}/{s.Id}");
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Create()
        {
            //string _restpath = "https://localhost:5000/SkiJumper";
            string _restpath = GetHostUrl().Content + CN();

            RestaurantVM s = new RestaurantVM();

            return View(s);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RestaurantVM s)
        {
            string _restpath = GetHostUrl().Content + CN();

            RestaurantVM result = new RestaurantVM();

            try
            {
                using (var htppClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(s);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");

                    using (var response = await htppClient.PostAsync($"{_restpath}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        s = JsonConvert.DeserializeObject<RestaurantVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

RestaurantManager.WebApp/Controllers/SecretController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantManager.WebApp.Controllers
{
    [Authorize(Roles = "Premium,Admin")]
    public class SecretController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RestaurantManager.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurantManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestaurantManager.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Index">Restaurant list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="Index">Manager list</a>
                        </li>
                        @{
                            if (User.IsInRole("Admin") || User.IsInRole("Premium"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Secret" asp-action="Index">*Materiały</a>

                                </li>
                            }
                            else
                            {
                                <li class="nav-link text-dark">
                                    <span style="color:darkgray">*Materiały</span>
                                </li>
                            }
                        }

                        @{
                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="PanelAdministracyjny" asp-action="Index">**Panel administracyjny</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-link text-dark">
                                    <span style="color:darkgray">**Panel administracyjny</span>
                                </li>
                            }
                        }
                        <li class="nav-item">

                            @*<a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Zarejestruj się</a>*@

                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Zarejestruj się</a>

                        </li>



                        @* Wylogowanie, Zalogowanie, Zalogowany user *@

                        @if (SignInManager.IsSignedIn(User))

                        {

                            <li class="nav-link text-dark">


                                @*<a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Witaj @User.Identity.Name</a>*@

                                Hello @User.Identity.Name

                            </li>

                            <li class="nav-link text-dark">


                                <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-right">
                                    <a href="javascript:document.getElementById('logoutForm').submit()">Wyloguj</a>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Zaloguj się</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RestaurantManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>